### ISSUE TITLE
Error : TIMEOUT during backend server running

### ISSUE THREAD

**Issue by josephyou7** [SerafinTech/ST-node-ethernet-ip#52]
## Current Behavior
 I am trying to make backend server with node. 
 It is running fine with attached program at first time but it has error after short 2 min. long 30 min.   
< Error Message >
C:\react-app\prodboard\backend\node_modules\ethernet-ip\src\controller\index.js:654
                        throw new Error(`<SCAN_GROUP>\n ${e.message}`);
                              ^
Error: <SCAN_GROUP>
 TIMEOUT occurred while writing Reading Tag Group.
    at C:\react-app\prodboard\backend\node_modules\ethernet-ip\src\controller\index.js:654:31
    at async Controller.scan (C:\react-app\prodboard\backend\node_modules\ethernet-ip\src\controller\index.js:647:13)

## Your Environment

* npm v9.8.1
* NPM ethernet-ip 1.2.5 
* Node Version Node.js v18.17.1
* Operating System window 10 Pro
*
[plc_server.txt](https://github.com/SerafinTech/ST-node-ethernet-ip/files/12753414/plc_server.txt)

**Comment by SerafinTech** [comment]
try ```const PLC = new Controller(false);``` on line 15 to use unconnected messaging.  Windows especially can cause a node process loop to pause for a few seconds which will disconnect you when using connected messaging.
